<?php

namespace App\Traits;

use Illuminate\Http\Response;

trait ApiResponser 
{

    public function successResponse($data, $code = Response::HTTP_OK)
    {
        // this code is changes since the message to return is already formatted by API responser of each sit
        return response($data, $code)->header('Content-Type', 'application/json');
    }


    public function errorResponse($message, $code)
    {
        // error response generated by api gateway itself

        return response()->json(['error' => $message, 'code' => $code], $code);
    }

    public function errorMessage($message, $code)
    {
        //error in ddsbe1 and 2
        return response($message, $code)->header('Content-Type', 'application/json');
    }

}